<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512">
<title></title>
<g id="icomoon-ignore">
</g>
<path d="M32 96h448v96h-448zM32 224h448v96h-448zM32 352h448v96h-448z"></path>
</svg>
